---
- name: Demonstrate vars_prompt
  hosts: localhost
  become: true
  remote_user: ansible
  vars_prompt:
   - prompt: "Enter your username"
     name: u_name
     private: no
   - prompt: "Enter your password"
     name: u_pass
     private: no
     default: test@123
  tasks:
   - name: Create a user {{u_name}}
     user:
      name: "{{u_name}}"
      password: "{{u_pass|password_hash('sha512')}}"
...