---
- name: Demonstrate variables
  hosts: localhost
  remote_user: anisble
  become: yes
  vars_files:
   - vars/prod_user.yml
  vars:
   u1_name: mysql

  tasks:
   - name: Task to create a user
     debug:
      msg: "{{u1_name}}"
      
...