---
- name: Play to demonstrate variables
  hosts: localhost
  remote_user: ansible
  become: yes
  vars:
   user1:
    name: skumar
    gecos: "Siva Kumar from DevOps team"
    home: /home/skumar
    shell: /bin/bash
   user2:
    name: roshan
    gecos: "Roshan from DevOps team"
    home: /home/roshan
    shell: /bin/bash
  tasks:
   - name: Task to print variable values
     debug:
      msg: |
            The user1 name is "{{user1.name}}"
            The user1 gecos is "{{user1.gecos}}"
            The user1 home dir is "{{user1.home}}"
            The user1 shell is "{{user1.shell}}"
            The user2 name is "{{user2.name}}"
            The user2 gecos is "{{user2.gecos}}"
            The user2 home dir is "{{user2.home}}"
            The user2 shell is "{{user2.shell}}"
...  