---
- name:  Play to create a file with some content
#use copy module to create a file and to put some content
  hosts: all
  become: true
  remote_user: ansible
  tasks:
   - name: task to create a file with some content
     copy:
      dest: /etc/.sec.conf #create a file
      content: "Username: ansible \nPassword:ansiansi"
      #put above line. \n used for new line
      mode: '0400' #file permissions
      owner: root
      group: root
  ...