---
#Ansible playbook can have multiple plays. This playbook demonstrates multiple plays in single palybook
- name: Play1 to install samba server
  hosts: [ 192.168.1.31, 192.168.1.32 ]
  become: true
  remote_user: ansible
  tasks:
   - name: Task to install samba
     yum:
      name: samba
      state: latest
#End of the play
#Below is the start of play2
- name: Play2 to start samba service
  hosts: [ 192.168.1.31, 192.168.1.32 ]
  become: true
  remote_user: ansible
  tasks:
   - name: Task to install samba - smbd
     service:
      name: smb
      state: started
   - name: Task to start nmbd
     service:
      name: nmb
      state: started
#End of the second play
#End of the playbook.
