---
- name: Demonstrate replace module in ansible
  hosts: localhost
  become: true
  remote_user: ansible
  tasks:
   - name: Task to replace the text using replace module
     replace: 
      path: /etc/iscsi/initiatorname.iscsi
      regexp: iqn.2024-06.in.myclass.brahmaiah:roshanhost
      replace: iqn.2024-07.in.sanjeevi.brahmaiah:sapdevdb
      backup: yes
...
#End of the play