---
#Play to disable selinux
- name: Play to modify /etc/selinux/config file 
  hosts: all
  become: true
  remote_user: ansible
  tasks:
   - name: Disable SELINUX
     lineinfile:
      path: /etc/selinux/config
      regexp:  ^SELINUX
      line: "SELINUX=disabled"
...
#End of the play