---
- name: play to demonstrate variables
  hosts: localhost
  vars:
   user:
    trainer:
     first_name: Captain
     last_name: America
    student:
     first_name: Brilliant
     last_name: Christ
  tasks:
   - name: Print Variable Values
     debug:
      msg: |
           "{{user['trainer']['first_name']}}" and "{{user['trainer']['last_name']}}"
           "{{user['student']['first_name']}}" and "{{user['student']['last_name']}}"
...
