---
#Play to deny direct root login using SSH
- name: Play to replace PermitRootLogin in /etc/ssh/sshd_config file
  hosts: all
  become: true
  remote_user: ansible
  tasks:
   - name: Replace PermitRootLogin
     lineinfile:
     path: /etc/ssh/sshd_config
     regexp: ^PermitRootLogin #Regular expression to search for this text, beginning line; thats why cap symbol
     line: "PermitRootLogin no" #Replace line with this
     backup: yes #take file backup before doing changes
   - name: Restart the ssh service after the config file change
     service:
      name: sshd
      state: restarted
...
#End of the play

    