---
- name: create a user, fetch password from the vault
  hosts: localhost
  become: true
  remote_user: ansible
  vars_files: /home/ansible/playbooks/ansi_sec.yml
  gather_facts: no
  tasks:
   - name: ask to create a user
     user: 
      name: myansi02
      password: "{{pass|password_hash('sha512')}}"
      state: present
...

   
   